"""add_details_to_member

Revision ID: fe9895996d45
Revises: d703c118ce99
Create Date: 2020-02-25 18:02:41.232899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9895996d45'
down_revision = 'd703c118ce99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.add_column('member', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('member', sa.Column('display_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'display_name')
    op.drop_column('member', 'bio')
    op.drop_column('member', 'avatar')
    # ### end Alembic commands ###
